MariaDB4j/MariaDB4j

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java

Syncrhonize db install to try to fix some intermittent test
failures when running parallel tests in maven that depend
on MariaDB4j.

Synchronize db install.

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java

Previously the empty password string was passed on to the mysql
command line tool resulting in mysql asking for a password and
stalling the test run.
Solves issue #66

Changed so that empty password string is treated the same as null

---

mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleDumpTest.java

@cortiz FYI, I think in the new MariaDB4jSampleDumpTest we have to waitForExit() for this test to be reliable - it currently probably just "happens" to work because it typically runs slow enough, but it's not truly concurrency safe as is. Adding the waitForExit() should do the trick though.

MariaDB4jSampleDumpTest should waitForExit() ManagedProcess

---

.travis.yml

As mvn fails on https://travis-ci.org/vorburger/MariaDB4j/builds/256517304 :
$ javac -J-Xmx32m -version
javac 1.8.0_131
$ mvn -f DBs/pom.xml clean install
Error: JAVA_HOME is not defined correctly.
We cannot execute /usr/lib/jvm/java-7-oracle/bin/java
The command "mvn -f DBs/pom.xml clean install" failed and exited with 1 during .

 Switch .travis.yml from oraclejdk7 to openjdk7

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/ManagedProcessRuntimeException.java
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDB4jService.java

from its @PostConstruct and @PreDestroy annotated methods
because of https://github.com/vorburger/MariaDB4j/issues/88

make MariaDB4jService throws ManagedProcessRuntimeException (fixes #88)

---

mariaDB4j/pom.xml

The artifact is managed in
org.springframework.boot:spring-boot-dependencies:2.0.2.RELEASE

remove <version>1.5.5 from mariadb-java-client which bumps it to 2.2.3

---

CONTRIBUTORS.md
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java

In one of our projects, we were planning to change the max_allowed_packet parameter but since this was automatically being set we wanted to confirm that our value would override the 64M value set automatically by MariaDB4j.
I had difficulty finding documentation confirming that the expected behavior of repeated command-line arguments is that the last value will be used.  In addition, having this set multiple times to different values could generally cause confusion.
This change simply checks the arguments that have been configured to see if it has already been set and only adds the parameter if it will not appear later.

Only set --max_allowed_packet if it is not in the configured arguments

---

mariaDB4j-maven-plugin/pom.xml

This fixes the Maven warnings which appear on the build:
```
[WARNING] Some problems were encountered while building the effective model for ch.vorburger.mariaDB4j:mariaDB4j-maven-plugin:maven-plugin:2.3.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ ch.vorburger.mariaDB4j:mariaDB4j-maven-plugin:[unknown-version], /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j-maven-plugin/pom.xml, line 181, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-invoker-plugin is missing. @ ch.vorburger.mariaDB4j:mariaDB4j-maven-plugin:[unknown-version], /home/vorburger/dev/MariaDB4j/git/MariaDB4j/mariaDB4j-maven-plugin/pom.xml, line 259, column 29
[WARNING]
[WARNING] It is highly recommended to fix …
```

use fixed versions of maven-jar-plugin and maven-invoker-plugin

---

checkstyle.xml

The LeftCurlyCheck maxLineLength property was removed from Checkstyle as it was a kludge for lines that were probably too long anyway.
I have simply removed the property from MariaDB4j, but left the LeftCurlyCheck active. There are no checkstyle errors following its removal.
I have only commited the required checkstyle.xml change. I am assuming dependabot will make the necessary pom.xml changes when #257 is rebased?

Fixes #257 - maven-checkstyle-plugin:3.1.0

---

CONTRIBUTORS.md
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/Util.java

The tryN method can return early when the procedure it runs is successful.
We are noticing that file copying is surprisingly slow on our RHEL CI hosts (some files taking a whole second to copy, repeated 5 times since tryN is called with n = 5). It's not clear why this is slow for us, but this will reduce the time needed by a factor of 5 (i.e. 2 minutes to 24 seconds).
The existing tests in ClasspathUnpackerTest look like suitable coverage and continue to pass.

Reduce file copying during classpath unpacking.

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
mariaDB4j-maven-plugin/pom.xml
mariaDB4j-maven-plugin/src/main/java/ch/vorburger/mariadb4j/AbstractRunMojo.java
mariaDB4j-maven-plugin/src/test/java/ch/vorburger/mariaDB4j/DbUtils.java
mariaDB4j-maven-plugin/src/test/java/ch/vorburger/mariaDB4j/Mariadb4jStartMojoTest.java
mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleDumpTest.java

Amongst others. Attempt to remove annoying warnings in build including:
1. deprecated closeQuielty methods. Replaced with try-with clauses which auto-close the resource. Moved allocation and close of resources to same methods so logic is clearer.
2. Removed Intellij IDEA specific SuppressWarnings. These caused subsequent warnings in Eclipse, VSCode and Intellij IDEA Communtity Edition without specific SQL plugins beng available.
3. Some checkstyle spacing warnings.
4. Added a SuppressWarnings("rawtype") for an unparameterised Map. Belive this warning is common to Eclipse, VSCode...
5. Remove unused imports.

Fixes #265 - clean more build warnings inc SQL SuppressWarnings

---

DBs/mariaDB4j-db-10.3/mariaDB4j-db-linux64-10.3/pom.xml
DBs/mariaDB4j-db-10.3/mariaDB4j-db-mac64-10.3/pom.xml
DBs/mariaDB4j-db-10.3/mariaDB4j-db-win32-10.3/pom.xml
DBs/mariaDB4j-db-10.3/mariaDB4j-db-winx64-10.3/pom.xml
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
mariaDB4j/pom.xml

NB that while there's already a 10.3.17 for Linux and Windows on https://downloads.mariadb.org, the latest Homebrew for Mac on Bintray is only 10.3.6 at https://bintray.com/homebrew/bottles/mariadb; see #292.

Bump MariaDB from 10.3.13 to 10.3.16

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java

The cleanup on exit feature checks if the `dataDir` folder is temporary and not the `baseDir` as intended.

Bug fix: dataDir is checked and not the baseDir

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
mariaDB4j/src/test/java/ch/vorburger/mariadb4j/StartSimulatedForAllPlatformsTest.java

As per #299 , exposing `installPreparation` (and rename the method to something more appropriate) to allow for subclassing of the `install` method to better suit individual project needs.

Rename installPreparation method to createMysqlInstallProcess and expose as protected

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java

Added an option to run database scripts less verbose. 
This runs fine with all unit tests, as you can see it almost changes nothing in the code!
But: If I create big databases for integration tests, it safes about a minute where it otherwise would scroll seemingly endlessly through the SQL script file content I already know. And without this option my log files are flooded with none-info. I could change the logging level, but all the other info from MariaDB4j is really informative, but not the script file, content I already know re-listed in excruciating detail.
This change is so small that I wouldn't insist on an entry in the contributors.md.

Added option to run database scripts less verbose

---

mariaDB4j-maven-plugin/pom.xml

What i did:
According to this commit [here](https://github.com/vorburger/MariaDB4j/pull/175/files/509d40b050ac4baa7227cdcf759598479795ee5f#diff-b14ceec598a3b9e47ae43b8a80978e45), i tried to fix a small change in comments, its a small fix which wont cause any harm.
thanks cc @vorburger

Maven Plugins:Fixing typo error

---

CONTRIBUTORS.md
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDB4jService.java

I think the start method should check if already started or not.
If you make the MariaDB4jSpringService bean from a config class, and you run source on it, then after initializing all beans, when PostConstruct is called, it calls start() and _resets_ the DB. I think this is not intentional, so I've added the necessary check.

[MariaDB4jService] Do not recreate the DB if already running

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/springframework/MariaDB4jSpringService.java

When running a service build in drone, I was trying to use mariadb4j as an embedded test database.
It refused to start as drone runs all the processes as root in the container and mysqld complained/refused to start as the user was root.
Found a workaround to specify the os user, to circumvent the problem.
I believe this will be helpful for users who will try to use with springboot in kubernetes environments.

Adding option to specify os user to the mysqld process

---

mariaDB4j-core/pom.xml

Libraries without a set automatic module name causes build warnings for
all clients who build with Java >= 9.
Also bump version of the Exec library, to use a version which has the
automatic module name set.
The following pull request for Exec adds an automatic module name:
https://github.com/vorburger/ch.vorburger.exec/pull/40

Issue #372: Add automatic module name to core

---

.travis.yml

Originally motivated by #488 (but then found to actually be unrelated to that - but still a good idea).

Run mvn verify instead of only package on Travis

---

mariaDB4j-maven-plugin/pom.xml

This doesn't fix https://github.com/vorburger/MariaDB4j/issues/488,
but still seems like a good idea to do, because the currently used
Maven version (or that test dependency) seems to use IO 2.4.1 as
well, so this does not appear to be required anymore now.

Remove fixed version of commons-io from Maven plugin dependencies

---

README.md
mariaDB4j-maven-plugin/src/it/mariadb4j-maven-plugin-test-basic/pom.xml
mariaDB4j-maven-plugin/src/it/mariadb4j-maven-plugin-test-basic/src/test/java/ch/vorburger/mariadb4j/mariadb4jmavenplugintest/basic/BasicUsageIT.java
mariaDB4j-maven-plugin/src/main/java/ch/vorburger/mariadb4j/AbstractRunMojo.java
mariaDB4j-maven-plugin/src/main/java/ch/vorburger/mariadb4j/StartMojo.java
mariaDB4j-maven-plugin/src/test/java/ch/vorburger/mariaDB4j/Mariadb4jStartMojoTest.java

There is currently no way to know on which port the `mariaDB4j-maven-plugin` has started the database so that integration tests can connect to it.
The only option is to hardcode a port number in the configuration of the `mariaDB4j-maven-plugin`, and use that same hardcoded port number in your test.
The old plugin version from mike10004 exposed a port number as Maven Project property (see [this file](https://github.com/mike10004/mariadb4j-maven-plugin/blob/master/mariadb4j-maven-plugin/src/main/java/com/github/mike10004/mariadb4jmavenplugin/Mariadb4jFindFreePortMojo.java)).
This PR does more or less the same. Instead of exposing the port number, it exposes the database URL. I also updated the readme to show how to retrieve that database URL and pass it to your integration tests as system …

mariaDB4j-maven-plugin: exposed database url as Maven Project property

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java

This should fix #340 .
The created outputstream is now closed using a process listener, which should get triggered when the dump is either done or has failed.
Alas, no test in this commit.
- I couldn't find any existing tests that perform a dump
- Even if there would be such a test, I would not know how to check from Java code whether that file stream is closed, unless I added some ugly code to grant me access to that stream
If you really want to have a test for this, some pointers in how you would approach testing this are welcome

When dumping the database, close the outputstream once the dump is done

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java

Because following the previous commit, it's no longer Windows specific.
This is backwards compatible because toWindowsPath() was private.
See https://github.com/vorburger/MariaDB4j/issues/501

Replace DB's toWindowsPath() with inline File.getCanonicalFile()

---

mariaDB4j-core/pom.xml

for https://github.com/vorburger/ch.vorburger.exec/pull/60
and https://github.com/vorburger/ch.vorburger.exec/pull/58
see https://github.com/vorburger/MariaDB4j/issues/501

Bump ch.vorburger.exec to 3.1.3 (fixes #501)

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfiguration.java
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
mariaDB4j-core/src/test/java/ch/vorburger/mariadb4j/tests/DBConfigurationBuilderTest.java
mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleOtherTest.java
mariaDB4j/src/test/resources/ch/vorburger/mariadb4j/characterTest.sql

Hi, I add default character set option in configuration. 
I know the addArgument function, but this action only effect with server side. 
When you want run script as another character set, "addArgument" function will doesn't work.

Support default character set configuration.

---

pom.xml

#509 related follow-up.
#549 won't be needed anymore.

Remove explict Log4j dependency (no longer needed now)

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfiguration.java

Remove `setDefaultCharacterSet()` from `DBConfiguration`, because this belongs (only) in `DBConfigurationBuilder`.

rm setDefaultCharacterSet from DBConfiguration (but not DBConfigurationBuilder)

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java

The Mac specific environment variable `DYLD_FALLBACK_LIBRARY_PATH` probably (?) should not end in space.
Does anyone using MariaDB4j on Mac want to test this?
I stumbled accross this while looking into #560.

Remove wrong space from DYLD_FALLBACK_LIBRARY_PATH

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfiguration.java
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBShutdownHook.java
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/springframework/MariaDB4jSpringService.java
mariaDB4j-core/src/test/java/ch/vorburger/mariadb4j/tests/DBConfigurationBuilderTest.java
mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceOverrideBySpringValueTest.java
mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceStandardDefaultsTest.java

This makes `--tmpdir` configurable, defaulting to `$TMPDIR/MariaDB4j/tmp/$PORT`. It should solve the issue of running multiple `mysqld` instances in parallel. See #602 for more details.

Add configurable tmpdir

---

README.md

Adds documentation derived from the example in [`MariaDB4jSampleTutorialTest.java`](https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java#L46-L58)

Add documentation for using native MariaDB binaries

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
pom.xml

Supersedes and closes #619.
@vorburger I think the error in #619 happened because springboot v2.7.0 [introduced a dependency on `flyway-mysql`](https://github.com/spring-projects/spring-boot/commit/4166429fd0d462d8a1948c77942477af624749b3), so the presence of both that and the mariadb driver on the classpath caused errors:
```
No suitable driver found for jdbc:mysql://localhost:36555/...
```
Updating the connection URL to use `mariadb` instead of `mysql` fixes it -- https://mariadb.com/kb/en/about-mariadb-connector-j/#jdbcmysql-scheme-compatibility

Update springboot version to 2.7.4

---

mariaDB4j-app/src/main/java/ch/vorburger/mariadb4j/springframework/boot/MariaDB4jApplication.java
mariaDB4j-springboot/src/main/resources/META-INF/spring.factories
pom.xml

Bump spring boot version to 3.0.4 . The main change was the removal of spring.factories in spring boot 3.X which i migrated to @Import in MariaDB4jApplication

PR-689 - Bump springboot.version from 2.7.5 to 3.0.4

---

mariaDB4j-core/pom.xml

for https://github.com/vorburger/ch.vorburger.exec/pull/103 and https://github.com/vorburger/ch.vorburger.exec/pull/96 for (finally) https://github.com/vorburger/MariaDB4j/issues/233!

Bump ch.vorburger.exec to 3.1.4 (fixes #233)

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

chore: Add github-actions ecosystem to Dependabot

---

CHANGELOG.md
mariaDB4j-app/pom.xml
mariaDB4j-core/pom.xml
mariaDB4j-maven-plugin/pom.xml
mariaDB4j-springboot/pom.xml
mariaDB4j/pom.xml
pom.xml

Because the upcoming upgrade of MariaDB binaries for Linux & Mac from 10.2.11 to 10.11.5 in #772 for #771 is a minor not an incremental (AKA patch or fix) version change; see e.g. https://semver.org.

chore: Switch 3.0.3-SNAPSHOT to 3.1.0-SNAPSHOT

---

.github/workflows/test.yaml

Folow up to #792 for #791 with a slightly better configuration.
This might address the pending Token-Permissions Code scanning Vulnerability alert Reporting (which also affects the OpenSSF Scorecard Report).

chore: Better Workflow Action Permissions (fixes #791)

---

mariaDB4j-core/pom.xml

See https://github.com/vorburger/ch.vorburger.exec/compare/exec-3.1.5...exec-3.2.0 for the "release notes" of what all this changes. The most important one is that this fixes https://github.com/vorburger/ch.vorburger.exec/issues/9.

fix: Upgrade ch.vorburger.exec from 3.1.5 to 3.2.0

---

.devcontainer/devcontainer.json
.github/dependabot.yml

To be able to [more easily] use (e.g.) GitHub Codespaces.

dev: DevContainer with Java 17 (instead of 11) 

---

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/Platform.java
mariaDB4j-core/src/test/java/ch/vorburger/mariadb4j/tests/DBConfigurationBuilderTest.java
mariaDB4j/src/test/java/ch/vorburger/mariadb4j/StartSimulatedForAllPlatformsTest.java

To temporarily override OS to simulate running on another one.
Originally motivated by exploring https://github.com/MariaDB4j/MariaDB4j/pull/1126/files#r2019771660 in #1134,
but now separately committing this as-is already (because that still does not quite work).

test: Include a method for cross-platform tests

---

DBs/mariaDB4j-db-11.4.5/mariaDB4j-db-winx64-11.4.5/prepare.xml
mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java

Follow-up to https://github.com/MariaDB4j/MariaDB4j/pull/1126/files#r2019771660,
to save ~17 MB (~27%) on JAR file size.

db: Package only mysql*.exe but not mariadb*.exe on winx64

---

.github/workflows/codeql-analysis.yml
.github/workflows/test.yaml

Now that I've deployed `winx64` from #1126 (with #1134) to Maven Central, this is no longer required (and would only be confusing, in the future).

ci: Do not mvn -f DB anymore

---

mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/springboot/autoconfigure/MariaDB4JSpringConfigurationTest.java
mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
pom.xml

This PR address addresses the manual fixes for this PR https://github.com/MariaDB4j/MariaDB4j/pull/1118 
Also addressing 
```
[ERROR] ch.vorburger.mariadb4j.springboot.autoconfigure.MariaDB4JSpringConfigurationTest.shouldAutoConfigureEmbeddedMariaDB -- Time elapsed: 11.52 s <<< ERROR!
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'ch.vorburger.mariadb4j.springboot.autoconfigure.MariaDB4jSpringConfiguration' available: expected single matching bean but found 2: mariaDB4jSpringConfiguration,ch.vorburger.mariadb4j.springboot.autoconfigure.MariaDB4jSpringConfiguration
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1514)
at …
```

Bump springboot.version from 3.3.4 to 3.4.4

---

mariaDB4j-springboot/pom.xml
mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceNewDefaultsOverriddenBySpringValueTest.java
mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceOverrideBySetTest.java
mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceOverrideBySpringValueTest.java
mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceStandardDefaultsTest.java
mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceTestSpringConfiguration.java

Fixes https://github.com/MariaDB4j/MariaDB4j/issues/1150
The problem 
---
was in the MariaDB4jSpringService class. The setDefaultPort method 
was not being picked up by the `@Value("${" + MariaDB4jSpringService.PORT + ":-1}")` injection because `@Value` was evaluated before the test-specific configuration is applied. That’s why the builder falls back to a random open port instead of the configured one.

(Fix) AssertionError: expected:<5678> but was:<49961> at ch.vorburger.mariadb4j.tests.springframework.*
