MariaDB4j/MariaDB4j

USERS.md
I will be happy if you accept this pull request.
=> add spwrap in the users list

pom.xml
thanks https://www.versioneye.com/java/ch.vorburger.mariadb4j:mariadb4j/2.2.2
=> Bump Spring framework version

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfiguration.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
see https://github.com/vorburger/MariaDB4j/issues/17
=> New boolean to enable security in DBConfiguration

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfiguration.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j-core/src/test/java/ch/vorburger/mariadb4j/tests/DBConfigurationBuilderTest.java
see https://github.com/vorburger/MariaDB4j/issues/36
see https://github.com/vorburger/MariaDB4j/issues/55
see https://github.com/vorburger/MariaDB4j/pull/60
=> New setDeletingTemporaryBaseAndDataDirsOnShutdown(false)

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/Util.java
motivated by analysis of the problem in https://github.com/vorburger/MariaDB4j/pull/100
@lde-avaleo if this seems like a good idea to you as well, can you reply with +1 to this PR?
=> chmod +x now prints info level log if file does not exist

.travis.yml, pom.xml
and run travis with 8 instead of 7
because Spring Boot 2 seems to require Java 8 (?)
=> compile with Java 8 instead of 6

mariaDB4j-maven-plugin/pom.xml, mariaDB4j-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
=> fix maven-plugin's lifecycle-mapping-metadata.xml for M2E

USERS.md
Finding this was a godsend for running bots on multi-VM's!!
=> add name to USERS.MD

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDB4jService.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDBOutputStreamLogDispatcher.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/springframework/MariaDB4jSpringService.java
=> Fix build warnings - import order, resolves issue#236

CONTRIBUTORS.md, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
Issue #259
First contribution! CONTRIBUTING.md suggests I just go ahead and fire in? I considered adding a String[] or String... argument to the the DB.source and DB.run methods to support "additionalArgs", but in the end felt that supporting "force" on its own was a worthwhile addition. Happy to make any suggested changes.
Kind regards, Gordon
=> DB.run - Continue on error (Issue #259)

.travis.yml
@mdindoffer do you think this is good idea? Given #262 (tx for having found and fixed it in #248)
=> disable ~/.m2 caching in .travis.yml (re. #262)

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfiguration.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
=> Fix build warnings - javadoc, issue #237

.gitignore
.vscode/ and .factorypath are roughly equivalent to Eclipse .settings/ and .classpath
=> Added Visual Studio Code project files to .gitignore.

.gitignore, DBs/mariaDB4j-db-10.3/mariaDB4j-db-linux64-10.3/pom.xml, DBs/mariaDB4j-db-10.3/mariaDB4j-db-linux64-10.3/prepare.xml, DBs/mariaDB4j-db-10.3/mariaDB4j-db-mac64-10.3/pom.xml, DBs/mariaDB4j-db-10.3/mariaDB4j-db-mac64-10.3/prepare.xml, DBs/mariaDB4j-db-10.3/mariaDB4j-db-win32-10.3/pom.xml, DBs/mariaDB4j-db-10.3/mariaDB4j-db-win32-10.3/prepare.xml, DBs/mariaDB4j-db-10.3/mariaDB4j-db-winx64-10.3/pom.xml, DBs/mariaDB4j-db-10.3/mariaDB4j-db-winx64-10.3/prepare.xml, DBs/mariaDB4j-db-10.3/pom.xml, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j/pom.xml
@vorburger This PR resolves #230 
@jtmuhone Would be able to review this pr
=> Features #230, Dynamic package with direct download of mariadb

.travis.yml
inspired by, but subset of, #267.
=> use mvn package instead of install in .travis.yml

DBs/mariaDB4j-db-10.3/pom.xml, DBs/pom.xml
very minor formatting fixes to POM XML changes introduced in #235.
@srbala FYI
=> fix intendation in pom.xml

mariaDB4j-maven-plugin/pom.xml
inspired by https://github.com/vorburger/MariaDB4j/pull/249
=> bump maven.version from 3.5.4 to 3.6.1

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
@GararJamal FYI, re. your #103.
=> Add null safety check to mysqldProcess.  Fixes #103.

.travis.yml, mariaDB4j-core/pom.xml, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j/pom.xml
=> Add jakarta.annotation-api to fix broken build on Java 11 (fixes #456)

mariaDB4j-maven-plugin/pom.xml, mariaDB4j-maven-plugin/src/test/java/ch/vorburger/mariaDB4j/StopMojoTest.java
as originally proposed by #480
see also https://github.com/mockito/mockito-kotlin/issues/383 for the code change required
=> Bump mockito-core from 3.5.15 to 4.1.0

mariaDB4j-maven-plugin/src/it/mariadb4j-maven-plugin-test-basic/pom.xml
see https://github.com/vorburger/MariaDB4j/issues/493
=> Use magic <version>@project.version@ in Maven Plugin IT

pom.xml
for https://github.com/vorburger/MariaDB4j/issues/495
=> Bump maven-release-plugin from 2.5.3 to 3.0.0-M4

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBShutdownHook.java
See the comment left in #488 and the class comment in the new `DBShutdownHook` class
=> Fixes #488

checkstyle.xml, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfiguration.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBShutdownHook.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDB4jService.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDBOutputStreamLogDispatcher.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/springframework/MariaDB4jSpringService.java, mariaDB4j-maven-plugin/src/main/java/ch/vorburger/mariadb4j/AbstractRunMojo.java, mariaDB4j-maven-plugin/src/main/java/ch/vorburger/mariadb4j/StartMojo.java, mariaDB4j-maven-plugin/src/main/java/ch/vorburger/mariadb4j/utils/DBSingleton.java, mariaDB4j-springboot/src/main/java/ch/vorburger/mariadb4j/springboot/autoconfigure/DataSourceAutoConfiguration.java, pom.xml
based on #498 from @glittle1972 
fixes #264
=> Enforce Checkstyle (fixes #264)

checkstyle.xml, mariaDB4j-app/src/test/java/ch/vorburger/mariadb4j/tests/springframework/boot/MariaDB4jApplicationTest.java, mariaDB4j-core/src/test/java/ch/vorburger/mariadb4j/tests/ClasspathUnpackerTest.java, mariaDB4j-core/src/test/java/ch/vorburger/mariadb4j/tests/DBConfigurationBuilderTest.java, mariaDB4j-maven-plugin/src/test/java/ch/vorburger/mariadb4j/DbUtils.java, mariaDB4j-maven-plugin/src/test/java/ch/vorburger/mariadb4j/MariaDB4jStartMojoTest.java, mariaDB4j-maven-plugin/src/test/java/ch/vorburger/mariadb4j/StopMojoTest.java, mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/springboot/autoconfigure/MariaDB4JSpringConfigurationTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/StartSimulatedForAllPlatformsTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleDumpTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleOtherTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jServiceTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/junit/MariaDB4jUnitRuleInitDBTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/junit/MariaDB4jUnitRuleOverrideDeaultPortTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceNewDefaultsOverridenBySpringValueTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceOverrideBySetTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceOverrideBySpringValueTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceStandardDefaultsTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceTestSpringConfiguration.java, pom.xml
Follow up to #498 (#500) re. #264
@glittle1972 FYI
=> Enable Checkstyle for src/test

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
See https://github.com/vorburger/MariaDB4j/issues/501
=> Spaces in windows paths are no longer replaced by %20

pom.xml
=> log4j dependencyManagement 2.15.0 instead of 2.14.1 (#509)

mariaDB4j-maven-plugin/pom.xml, pom.xml
=> Fix failing release due to Checkstyle in generated-sources (fixes #511)

mariaDB4j-core/pom.xml, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfiguration.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j-core/src/test/java/ch/vorburger/mariadb4j/tests/DBConfigurationBuilderTest.java, mariaDB4j/pom.xml, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java, pom.xml
=> (WIP) Support using locally installed MariaDB (#560)

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
=> set source api default charact set to utf8

README.md, mariaDB4j-app/pom.xml, mariaDB4j-core/pom.xml, mariaDB4j-maven-plugin/pom.xml, mariaDB4j-springboot/pom.xml, mariaDB4j/pom.xml, pom.xml
Due to the upcoming  switch from Java 11 to Java 17, which warrants a major version upgrade for this project.
See #650.
=> Change  2.6.1 version in POM to 3.0.0

mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
=> test: Improve testLocalMariaDB() failure (fixes #681)

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDB4jService.java, pom.xml
Added import for jakarta annotation api and migrated javax.annotation.* import to jakarta.annotation.*
=> PR-648 - Support for jakarta annotation

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/springframework/MariaDB4jSpringService.java
mariaDB4j.dbCharset=utf8mb4 for --character-set-server=utf8mb4
=> feat: database charset configable

.github/workflows/buildTestWindows.yml
See #715 for why.
@jejanim FYI
=> build: Remove dorny/test-reporter GitHub Action (see #715)

mariaDB4j-core/pom.xml
This includes the following noteworth changes:
* https://github.com/vorburger/ch.vorburger.exec/pull/110
* https://github.com/vorburger/ch.vorburger.exec/pull/112
* https://github.com/vorburger/ch.vorburger.exec/pull/115
=> Bump ch.vorburger.exec to 3.1.5

CHANGELOG.md
I forgot to do this in #696 ...
=> docs: Add missing CHANGELOG for 3.0.1

.github/workflows/scorecard.yml
=> chore: Create scorecard.yml (see #661)

README.md
see #786
[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/MariaDB4j/MariaDB4j/main.svg)](https://results.pre-commit.ci/latest/github/MariaDB4j/MariaDB4j/main)
=> docs: Add Pre-Commit Hooks badge to README (see #786)

pom.xml
see https://maven.apache.org/guides/mini/guide-reproducible-builds.html
for https://www.bestpractices.dev/en/projects/7865
re. #661
=> fix: Reproducible Builds (re. #661)

.github/workflows/test.yaml, README.md
=> chore: Limit Workflow Action Permissions (fixes #791)

.mvn/wrapper/maven-wrapper.properties, README.md, pom.xml
=> Use JEP 247 to fix broken build under Java 21

mariaDB4j-app/pom.xml, mariaDB4j-core/pom.xml, mariaDB4j-maven-plugin/pom.xml, mariaDB4j-springboot/pom.xml, mariaDB4j/pom.xml, pom.xml
=> Maven Release Plugin prepares future 3.1.1

CHANGELOG.md
=> docs: Change Log for v3.1.0 release (fixes #918)

README.md
=> docs: Change the (never released) 3.0.2 to 3.1.0 on README

CHANGELOG.md, CONTRIBUTORS.md, README.md, USERS.md, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j-maven-plugin/src/test/java/ch/vorburger/mariadb4j/StopMojoTest.java, mariaDB4j-pom-lite/pom.xml, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleDumpTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleOtherTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/junit/MariaDB4jUnitRuleOverrideDefaultPortTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceNewDefaultsOverriddenBySpringValueTest.java, pom.xml
This PR fixes a few typos I spotted in the project. It also corrects some broken and some outdated links.
=> Fix typos, fix broken links, amend links

README.md
Thanks https://star-history.com!
=> Add Star History to README

mariaDB4j-core/pom.xml
see https://github.com/vorburger/ch.vorburger.exec/releases/tag/exec-3.3.0
and https://github.com/vorburger/ch.vorburger.exec/issues/212
@mosesn @duttonw FYI
=> Upgrade ch.vorburger.exec from 3.2.0 to 3.3.0

.github/workflows/test.yaml
=> Run CI on Ubuntu 22.04 instead of latest 24.04 (see #1045)

README.md
And reformat to introduce a "Related Projects" section.
@ruroru TX for maintaining the now linked Clojure wrapper!
=> Add Clojure wrapper to README

.devcontainer/devcontainer.json, .github/workflows/test.yaml, CHANGELOG.md, DBs/mariaDB4j-db-11.4.5/mariaDB4j-db-11.4.5-linux-x86_64/pom.xml, DBs/mariaDB4j-db-11.4.5/mariaDB4j-db-11.4.5-linux-x86_64/prepare.xml, README.md, mariaDB4j-app/pom.xml, mariaDB4j-core/pom.xml, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j-maven-plugin/pom.xml, mariaDB4j-springboot/pom.xml, mariaDB4j/pom.xml, pom.xml
See #1120.
This will not work on CI as-is just yet - I'll need to first push the new DB to Maven Central...
=> db: Add mariaDB4j-db-11.4.5-linux-x86_64 (see #1120)

.github/workflows/test.yaml
References: https://github.com/MariaDB4j/MariaDB4j/issues/1045
=> Run unit tests on ubuntu-24.04

DBs/mariaDB4j-db-11.4.5/mariaDB4j-db-11.4.5-macos-arm64/pom.xml, DBs/mariaDB4j-db-11.4.5/mariaDB4j-db-11.4.5-macos-arm64/prepare.xml, README.md, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j/pom.xml, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
=> db: Add mariaDB4j-db-11.4.5-macos-arm64 (see #497)

mariaDB4j-maven-plugin/src/main/java/ch/vorburger/mariadb4j/AbstractRunMojo.java, mariaDB4j-maven-plugin/src/main/java/ch/vorburger/mariadb4j/utils/DBSingleton.java, pom.xml
incl. required manual fixes on top of #1119.
=> Bump Checkstyle from 10.17.0 to 10.21.4

.github/workflows/codeql-analysis.yml, .github/workflows/test.yaml, CONTRIBUTORS.md, DBs/mariaDB4j-db-11.4.5/mariaDB4j-db-winx64-11.4.5/pom.xml, DBs/mariaDB4j-db-11.4.5/mariaDB4j-db-winx64-11.4.5/prepare.xml, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j/pom.xml, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
Adds Windows MariaDB 11.4.5 binaries.
=> Windows MariaDB 11.4.5 upgrade.

.github/workflows/test.yaml
Follow-up to #1126
@TheKnowles FYI
=> ci: Use fixed revision of ankane/setup-mariadb

README.md, SECURITY.md
=> docs: Clarify Java version support policy on README

README.md
=> docs: Mention macOS Monterey incompatibility on README (fixes #1149)

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfiguration.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBShutdownHook.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/Util.java, mariaDB4j-core/src/test/java/ch/vorburger/mariadb4j/tests/DBConfigurationBuilderTest.java, mariaDB4j-maven-plugin/src/main/java/ch/vorburger/mariadb4j/AbstractRunMojo.java, mariaDB4j-springboot/src/main/java/ch/vorburger/mariadb4j/springframework/MariaDB4jSpringService.java, mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceOverrideBySetTest.java, mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceOverrideBySpringValueTest.java, mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/tests/springframework/MariaDB4jSpringServiceStandardDefaultsTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/StartSimulatedForAllPlatformsTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleOtherTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
for baseDir, libDir, dataDir, tmpDir 
Fixes #1140.
=> feat: DBConfiguration & Co. with File instead String

CHANGELOG.md, docs/contrib.md, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBShutdownHook.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/ManagedProcessRuntimeException.java, mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDBOutputStreamLogDispatcher.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleOtherTest.java, mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/StartManyTimes.java
=> docs: CHANGELOG

README.md
=> docs: Add jvm-repo-rebuild/reproducible-central link to README

.pre-commit-config.yaml
Inspired by https://github.com/enola-dev/enola/blob/c72f5d271897330f11462df865dd77e44a2d62fa/.pre-commit-config.yaml#L28
=> chore: Add additional pre-commit-hooks

mariaDB4j-app/pom.xml, mariaDB4j-core/pom.xml, mariaDB4j-junit/pom.xml, mariaDB4j-maven-plugin/pom.xml, mariaDB4j-springboot/pom.xml, mariaDB4j/pom.xml, pom.xml
re. #1137 (and triggered by my own confusion about which version is what, for #1248)
=> chore: Increment project version from 3.2.0-SNAPSHOT to 3.2.1-SNAPSHOT

mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
A very minor follow-up to #1218 from @TheKnowles.
/CC FYI @Osiris-Team (who reviewed #1218) and @Muta-Jonathan (who commented on #1217).
=> fix: Include cause in re-throw

docs/contrib.md
=> docs: Revise release process (see #1250)
